import type { Appointment, Patient, VisitRecord, ConsentRecord, CommonAcupoint, CommonFormula, CommonTemplate } from '@/types'
import { startOfDay, addHours, addMinutes, subDays } from 'date-fns'

const today = startOfDay(new Date())

export const DEMO_PATIENTS: Patient[] = [
  {
    id: 'p1',
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-03-20T00:00:00Z',
    first_name: '明',
    last_name: '张',
    phone: '138-0000-1111',
    email: 'zhangming@example.com',
    date_of_birth: '1985-06-15',
    gender: 'male',
    allergies: '青霉素',
    medical_history: '高血压',
    emergency_contact_name: '张丽',
    emergency_contact_phone: '138-0000-9999',
    notes: '定期针灸治疗腰痛',
    consent_signed: true,
    last_visit_at: '2025-03-20T10:00:00Z',
    is_archived: false,
  },
  {
    id: 'p2',
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-03-22T00:00:00Z',
    first_name: '丽华',
    last_name: '李',
    phone: '139-0000-2222',
    email: 'lilihua@example.com',
    date_of_birth: '1990-11-20',
    gender: 'female',
    allergies: '',
    medical_history: '',
    notes: '失眠，肝气郁结',
    consent_signed: true,
    last_visit_at: '2025-03-22T14:00:00Z',
    is_archived: false,
  },
  {
    id: 'p3',
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-03-25T00:00:00Z',
    first_name: '伟',
    last_name: '王',
    phone: '137-0000-3333',
    date_of_birth: '1978-03-08',
    gender: 'male',
    allergies: '花粉',
    medical_history: '胃溃疡史',
    notes: '',
    consent_signed: false,
    last_visit_at: '2025-03-25T09:00:00Z',
    is_archived: false,
  },
  {
    id: 'p4',
    created_at: '2025-03-10T00:00:00Z',
    updated_at: '2025-03-24T00:00:00Z',
    first_name: '小红',
    last_name: '刘',
    phone: '136-0000-4444',
    email: 'liuxiaohong@example.com',
    date_of_birth: '1995-08-12',
    gender: 'female',
    notes: '颈椎不适，初诊',
    consent_signed: true,
    is_archived: false,
  },
  {
    id: 'p5',
    created_at: '2025-03-15T00:00:00Z',
    updated_at: '2025-03-26T00:00:00Z',
    first_name: '国强',
    last_name: '陈',
    phone: '135-0000-5555',
    date_of_birth: '1968-01-25',
    gender: 'male',
    medical_history: '糖尿病、高血脂',
    allergies: '磺胺类药物',
    notes: '中药调理，每两周复诊',
    consent_signed: true,
    last_visit_at: '2025-03-19T15:00:00Z',
    is_archived: false,
  },
]

export const DEMO_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1', created_at: '2025-03-25T00:00:00Z', updated_at: '2025-03-25T00:00:00Z',
    patient_id: 'p1', start_time: addHours(today, 9).toISOString(), end_time: addMinutes(addHours(today, 9), 60).toISOString(),
    service_type: 'acupuncture', status: 'confirmed', notes: '腰痛针灸第6次',
    sms_confirmation_sent: true, sms_reminder_24h_sent: true, sms_reminder_2h_sent: false,
    patient: DEMO_PATIENTS[0],
  },
  {
    id: 'a2', created_at: '2025-03-25T00:00:00Z', updated_at: '2025-03-25T00:00:00Z',
    patient_id: 'p2', start_time: addHours(today, 10).toISOString(), end_time: addMinutes(addHours(today, 10), 45).toISOString(),
    service_type: 'herbal_consultation', status: 'arrived', notes: '失眠中药调整',
    sms_confirmation_sent: true, sms_reminder_24h_sent: true, sms_reminder_2h_sent: true,
    patient: DEMO_PATIENTS[1],
  },
  {
    id: 'a3', created_at: '2025-03-25T00:00:00Z', updated_at: '2025-03-25T00:00:00Z',
    patient_id: 'p4', start_time: addHours(today, 11).toISOString(), end_time: addMinutes(addHours(today, 11), 90).toISOString(),
    service_type: 'initial_consultation', status: 'scheduled', notes: '颈椎不适，新患者',
    sms_confirmation_sent: true, sms_reminder_24h_sent: false, sms_reminder_2h_sent: false,
    patient: DEMO_PATIENTS[3],
  },
  {
    id: 'a4', created_at: '2025-03-25T00:00:00Z', updated_at: '2025-03-25T00:00:00Z',
    patient_id: 'p5', start_time: addHours(today, 14).toISOString(), end_time: addMinutes(addHours(today, 14), 60).toISOString(),
    service_type: 'follow_up', status: 'confirmed', notes: '中药复诊，查看上次方效果',
    sms_confirmation_sent: true, sms_reminder_24h_sent: true, sms_reminder_2h_sent: false,
    patient: DEMO_PATIENTS[4],
  },
  {
    id: 'a5', created_at: '2025-03-25T00:00:00Z', updated_at: '2025-03-25T00:00:00Z',
    patient_id: 'p3', start_time: addHours(today, 16).toISOString(), end_time: addMinutes(addHours(today, 16), 60).toISOString(),
    service_type: 'acupuncture', status: 'completed', notes: '胃痛针灸第3次',
    sms_confirmation_sent: true, sms_reminder_24h_sent: true, sms_reminder_2h_sent: true,
    patient: DEMO_PATIENTS[2],
  },
]

// Demo visit records
export const DEMO_VISITS: VisitRecord[] = [
  {
    id: 'v1', created_at: '2025-03-20T10:00:00Z', updated_at: '2025-03-20T11:00:00Z',
    patient_id: 'p1', appointment_id: undefined, visit_datetime: '2025-03-20T10:00:00Z',
    chief_complaint: '腰部酸痛，弯腰加重，晨起僵硬',
    treatment_type: 'acupuncture',
    tongue_diagnosis: '舌淡红，苔薄白',
    pulse_diagnosis: '脉弦细',
    tcm_pattern: '肾虚腰痛',
    doctor_notes: '第5次治疗，腰痛较前改善约50%。继续针灸治疗。',
    acupuncture_details: [{
      id: 'ad1', visit_record_id: 'v1',
      acupoints: ['BL23', 'BL25', 'GV4', 'GB30', 'BL40', 'KI3'],
      needle_retention_min: 30, needle_gauge: '0.25x40mm',
      technique_notes: '平补平泻，BL23加温针灸',
      moxa_used: true, electro_stim_used: false, cupping_used: true,
    }],
  },
  {
    id: 'v2', created_at: '2025-03-13T10:00:00Z', updated_at: '2025-03-13T11:00:00Z',
    patient_id: 'p1', visit_datetime: '2025-03-13T10:00:00Z',
    chief_complaint: '腰痛持续，右侧为主',
    treatment_type: 'acupuncture',
    tongue_diagnosis: '舌淡红，苔薄白',
    pulse_diagnosis: '脉弦',
    tcm_pattern: '肾虚腰痛',
    doctor_notes: '第4次治疗，加大肾俞穴刺激量。',
    acupuncture_details: [{
      id: 'ad2', visit_record_id: 'v2',
      acupoints: ['BL23', 'BL25', 'GV4', 'BL40', 'KI3'],
      needle_retention_min: 25, moxa_used: true, electro_stim_used: false, cupping_used: false,
    }],
  },
  {
    id: 'v3', created_at: '2025-03-22T14:00:00Z', updated_at: '2025-03-22T15:00:00Z',
    patient_id: 'p2', visit_datetime: '2025-03-22T14:00:00Z',
    chief_complaint: '失眠多梦，入睡困难，烦躁易怒',
    treatment_type: 'acupuncture_and_herbal',
    tongue_diagnosis: '舌红，苔薄黄',
    pulse_diagnosis: '脉弦数',
    tcm_pattern: '肝郁化火',
    doctor_notes: '上次逍遥散服用7天后入睡时间缩短，仍有多梦。加减方中增加酸枣仁、夜交藤安神。',
    acupuncture_details: [{
      id: 'ad3', visit_record_id: 'v3',
      acupoints: ['HT7', 'SP6', 'LR3', 'GV20', 'EX-HN1', 'PC6'],
      needle_retention_min: 30, moxa_used: false, electro_stim_used: false, cupping_used: false,
    }],
    herbal_prescriptions: [{
      id: 'hp1', visit_record_id: 'v3',
      formula_name: '逍遥散加减',
      instructions: '每日一剂，水煎服，分早晚两次温服',
      duration_days: 14, refills: 0,
      herb_items: [
        { id: 'hi1', prescription_id: 'hp1', herb_name_pinyin: 'Chai Hu', herb_name_chinese: '柴胡', dosage_grams: 10, sort_order: 0 },
        { id: 'hi2', prescription_id: 'hp1', herb_name_pinyin: 'Bai Shao', herb_name_chinese: '白芍', dosage_grams: 15, sort_order: 1 },
        { id: 'hi3', prescription_id: 'hp1', herb_name_pinyin: 'Dang Gui', herb_name_chinese: '当归', dosage_grams: 10, sort_order: 2 },
        { id: 'hi4', prescription_id: 'hp1', herb_name_pinyin: 'Suan Zao Ren', herb_name_chinese: '酸枣仁', dosage_grams: 20, sort_order: 3 },
        { id: 'hi5', prescription_id: 'hp1', herb_name_pinyin: 'Ye Jiao Teng', herb_name_chinese: '夜交藤', dosage_grams: 15, sort_order: 4 },
        { id: 'hi6', prescription_id: 'hp1', herb_name_pinyin: 'Fu Ling', herb_name_chinese: '茯苓', dosage_grams: 15, sort_order: 5 },
        { id: 'hi7', prescription_id: 'hp1', herb_name_pinyin: 'Gan Cao', herb_name_chinese: '甘草', dosage_grams: 6, sort_order: 6 },
      ],
    }],
  },
  {
    id: 'v4', created_at: '2025-03-15T14:00:00Z', updated_at: '2025-03-15T15:00:00Z',
    patient_id: 'p2', visit_datetime: '2025-03-15T14:00:00Z',
    chief_complaint: '失眠2月余，入睡困难',
    treatment_type: 'herbal',
    tongue_diagnosis: '舌红，苔薄',
    pulse_diagnosis: '脉弦',
    tcm_pattern: '肝气郁结',
    doctor_notes: '初诊，先以逍遥散疏肝理气为主，服药7天后复诊。',
    herbal_prescriptions: [{
      id: 'hp2', visit_record_id: 'v4',
      formula_name: '逍遥散',
      instructions: '每日一剂，水煎服，分早晚两次温服',
      duration_days: 7,
      herb_items: [
        { id: 'hi8', prescription_id: 'hp2', herb_name_pinyin: 'Chai Hu', herb_name_chinese: '柴胡', dosage_grams: 10, sort_order: 0 },
        { id: 'hi9', prescription_id: 'hp2', herb_name_pinyin: 'Bai Shao', herb_name_chinese: '白芍', dosage_grams: 12, sort_order: 1 },
        { id: 'hi10', prescription_id: 'hp2', herb_name_pinyin: 'Dang Gui', herb_name_chinese: '当归', dosage_grams: 10, sort_order: 2 },
        { id: 'hi11', prescription_id: 'hp2', herb_name_pinyin: 'Fu Ling', herb_name_chinese: '茯苓', dosage_grams: 15, sort_order: 3 },
        { id: 'hi12', prescription_id: 'hp2', herb_name_pinyin: 'Bai Zhu', herb_name_chinese: '白术', dosage_grams: 10, sort_order: 4 },
        { id: 'hi13', prescription_id: 'hp2', herb_name_pinyin: 'Gan Cao', herb_name_chinese: '甘草', dosage_grams: 6, sort_order: 5 },
        { id: 'hi14', prescription_id: 'hp2', herb_name_pinyin: 'Bo He', herb_name_chinese: '薄荷', dosage_grams: 3, processing_method: '后下', sort_order: 6 },
        { id: 'hi15', prescription_id: 'hp2', herb_name_pinyin: 'Sheng Jiang', herb_name_chinese: '生姜', dosage_grams: 3, sort_order: 7 },
      ],
    }],
  },
  {
    id: 'v5', created_at: '2025-03-25T09:00:00Z', updated_at: '2025-03-25T10:00:00Z',
    patient_id: 'p3', visit_datetime: '2025-03-25T09:00:00Z',
    chief_complaint: '胃脘胀痛，食后加重，嗳气反酸',
    treatment_type: 'acupuncture',
    tongue_diagnosis: '舌淡，苔白腻',
    pulse_diagnosis: '脉弦滑',
    tcm_pattern: '肝胃不和',
    doctor_notes: '第3次治疗，胃痛明显好转，嗳气减少。',
    acupuncture_details: [{
      id: 'ad4', visit_record_id: 'v5',
      acupoints: ['CV12', 'ST36', 'PC6', 'LR3', 'SP4', 'ST21'],
      needle_retention_min: 25, moxa_used: true, electro_stim_used: false, cupping_used: false,
    }],
  },
  {
    id: 'v6', created_at: '2025-03-19T15:00:00Z', updated_at: '2025-03-19T16:00:00Z',
    patient_id: 'p5', visit_datetime: '2025-03-19T15:00:00Z',
    chief_complaint: '口渴多饮，疲倦乏力，血糖控制不佳',
    treatment_type: 'herbal',
    tongue_diagnosis: '舌红少津',
    pulse_diagnosis: '脉细数',
    tcm_pattern: '气阴两虚',
    doctor_notes: '配合西药降糖治疗，中药以益气养阴为主。血糖空腹7.8，餐后11.2。',
    herbal_prescriptions: [{
      id: 'hp3', visit_record_id: 'v6',
      formula_name: '六味地黄丸加减',
      instructions: '每日一剂，水煎服。忌辛辣油腻。',
      duration_days: 14,
      herb_items: [
        { id: 'hi16', prescription_id: 'hp3', herb_name_pinyin: 'Shu Di Huang', herb_name_chinese: '熟地黄', dosage_grams: 15, sort_order: 0 },
        { id: 'hi17', prescription_id: 'hp3', herb_name_pinyin: 'Shan Yao', herb_name_chinese: '山药', dosage_grams: 15, sort_order: 1 },
        { id: 'hi18', prescription_id: 'hp3', herb_name_pinyin: 'Shan Zhu Yu', herb_name_chinese: '山茱萸', dosage_grams: 10, sort_order: 2 },
        { id: 'hi19', prescription_id: 'hp3', herb_name_pinyin: 'Huang Qi', herb_name_chinese: '黄芪', dosage_grams: 20, sort_order: 3 },
        { id: 'hi20', prescription_id: 'hp3', herb_name_pinyin: 'Tian Hua Fen', herb_name_chinese: '天花粉', dosage_grams: 15, sort_order: 4 },
        { id: 'hi21', prescription_id: 'hp3', herb_name_pinyin: 'Mai Dong', herb_name_chinese: '麦冬', dosage_grams: 12, sort_order: 5 },
      ],
    }],
  },
]

// Demo consent records
export const DEMO_CONSENTS: ConsentRecord[] = [
  {
    id: 'c1', created_at: '2025-01-15T09:00:00Z', patient_id: 'p1',
    consent_type: 'initial_consent', signature_url: '', signed_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 'c2', created_at: '2025-01-15T09:05:00Z', patient_id: 'p1',
    consent_type: 'acupuncture_consent', signature_url: '', signed_at: '2025-01-15T09:05:00Z',
  },
  {
    id: 'c3', created_at: '2025-02-01T13:30:00Z', patient_id: 'p2',
    consent_type: 'initial_consent', signature_url: '', signed_at: '2025-02-01T13:30:00Z',
  },
  {
    id: 'c4', created_at: '2025-03-10T10:00:00Z', patient_id: 'p4',
    consent_type: 'initial_consent', signature_url: '', signed_at: '2025-03-10T10:00:00Z',
  },
  {
    id: 'c5', created_at: '2025-03-10T10:05:00Z', patient_id: 'p4',
    consent_type: 'acupuncture_consent', signature_url: '', signed_at: '2025-03-10T10:05:00Z',
  },
  {
    id: 'c6', created_at: '2025-03-15T14:30:00Z', patient_id: 'p5',
    consent_type: 'initial_consent', signature_url: '', signed_at: '2025-03-15T14:30:00Z',
  },
]

// Demo acupoints (subset for quick selection)
export const DEMO_ACUPOINTS: CommonAcupoint[] = [
  { id: 'ap1', code: 'LI4', name_pinyin: 'He Gu', name_chinese: '合谷', meridian: '手阳明大肠经', common_uses: '头痛、牙痛、感冒', is_favorite: true, sort_order: 0 },
  { id: 'ap2', code: 'ST36', name_pinyin: 'Zu San Li', name_chinese: '足三里', meridian: '足阳明胃经', common_uses: '胃痛、腹胀、虚劳', is_favorite: true, sort_order: 1 },
  { id: 'ap3', code: 'SP6', name_pinyin: 'San Yin Jiao', name_chinese: '三阴交', meridian: '足太阴脾经', common_uses: '失眠、月经不调、消化不良', is_favorite: true, sort_order: 2 },
  { id: 'ap4', code: 'LR3', name_pinyin: 'Tai Chong', name_chinese: '太冲', meridian: '足厥阴肝经', common_uses: '头痛、眩晕、肝气郁结', is_favorite: true, sort_order: 3 },
  { id: 'ap5', code: 'PC6', name_pinyin: 'Nei Guan', name_chinese: '内关', meridian: '手厥阴心包经', common_uses: '心悸、失眠、恶心', is_favorite: true, sort_order: 4 },
  { id: 'ap6', code: 'HT7', name_pinyin: 'Shen Men', name_chinese: '神门', meridian: '手少阴心经', common_uses: '失眠、心悸、焦虑', is_favorite: true, sort_order: 5 },
  { id: 'ap7', code: 'GV20', name_pinyin: 'Bai Hui', name_chinese: '百会', meridian: '督脉', common_uses: '头痛、眩晕、失眠', is_favorite: true, sort_order: 6 },
  { id: 'ap8', code: 'BL23', name_pinyin: 'Shen Shu', name_chinese: '肾俞', meridian: '足太阳膀胱经', common_uses: '腰痛、肾虚、耳鸣', is_favorite: true, sort_order: 7 },
  { id: 'ap9', code: 'CV12', name_pinyin: 'Zhong Wan', name_chinese: '中脘', meridian: '任脉', common_uses: '胃痛、腹胀、呕吐', is_favorite: false, sort_order: 8 },
  { id: 'ap10', code: 'CV4', name_pinyin: 'Guan Yuan', name_chinese: '关元', meridian: '任脉', common_uses: '虚劳、腹痛、月经不调', is_favorite: false, sort_order: 9 },
  { id: 'ap11', code: 'BL25', name_pinyin: 'Da Chang Shu', name_chinese: '大肠俞', meridian: '足太阳膀胱经', common_uses: '腰痛、腹泻、便秘', is_favorite: false, sort_order: 10 },
  { id: 'ap12', code: 'BL40', name_pinyin: 'Wei Zhong', name_chinese: '委中', meridian: '足太阳膀胱经', common_uses: '腰背痛、膝痛', is_favorite: false, sort_order: 11 },
  { id: 'ap13', code: 'GB30', name_pinyin: 'Huan Tiao', name_chinese: '环跳', meridian: '足少阳胆经', common_uses: '腰腿痛、坐骨神经痛', is_favorite: false, sort_order: 12 },
  { id: 'ap14', code: 'KI3', name_pinyin: 'Tai Xi', name_chinese: '太溪', meridian: '足少阴肾经', common_uses: '肾虚、腰痛、耳鸣', is_favorite: false, sort_order: 13 },
  { id: 'ap15', code: 'GV4', name_pinyin: 'Ming Men', name_chinese: '命门', meridian: '督脉', common_uses: '腰痛、肾阳虚', is_favorite: false, sort_order: 14 },
  { id: 'ap16', code: 'ST21', name_pinyin: 'Liang Men', name_chinese: '梁门', meridian: '足阳明胃经', common_uses: '胃痛、食欲不振', is_favorite: false, sort_order: 15 },
  { id: 'ap17', code: 'SP4', name_pinyin: 'Gong Sun', name_chinese: '公孙', meridian: '足太阴脾经', common_uses: '胃痛、腹胀', is_favorite: false, sort_order: 16 },
  { id: 'ap18', code: 'EX-HN1', name_pinyin: 'Si Shen Cong', name_chinese: '四神聪', meridian: '经外奇穴', common_uses: '头痛、失眠、健忘', is_favorite: false, sort_order: 17 },
]

// Demo templates
export const DEMO_TEMPLATES: CommonTemplate[] = [
  { id: 't1', category: 'chief_complaint', title: '腰痛', content: '腰部酸痛，弯腰加重', sort_order: 0, is_active: true },
  { id: 't2', category: 'chief_complaint', title: '头痛', content: '头痛反复发作', sort_order: 1, is_active: true },
  { id: 't3', category: 'chief_complaint', title: '失眠', content: '入睡困难，多梦易醒', sort_order: 2, is_active: true },
  { id: 't4', category: 'chief_complaint', title: '胃痛', content: '胃脘胀痛，食后加重', sort_order: 3, is_active: true },
  { id: 't5', category: 'chief_complaint', title: '颈痛', content: '颈部僵硬疼痛，转头受限', sort_order: 4, is_active: true },
  { id: 't6', category: 'chief_complaint', title: '月经不调', content: '月经周期不规律，经量偏少', sort_order: 5, is_active: true },
  { id: 't7', category: 'doctor_notes', title: '改善', content: '症状较前改善，继续治疗。', sort_order: 0, is_active: true },
  { id: 't8', category: 'doctor_notes', title: '首诊', content: '首次就诊，制定治疗方案。', sort_order: 1, is_active: true },
  { id: 't9', category: 'doctor_notes', title: '复诊调方', content: '复诊，根据症状变化调整处方。', sort_order: 2, is_active: true },
  { id: 't10', category: 'instructions', title: '针灸后注意', content: '针灸后2小时内避免洗浴，注意保暖，多饮温水。', sort_order: 0, is_active: true },
  { id: 't11', category: 'instructions', title: '中药服用', content: '每日一剂，水煎服，分早晚两次温服。忌辛辣、生冷、油腻食物。', sort_order: 1, is_active: true },
]

// Demo formulas
export const DEMO_FORMULAS: CommonFormula[] = [
  {
    id: 'f1', name_pinyin: 'Xiao Yao San', name_chinese: '逍遥散', category: '疏肝理气',
    instructions: '每日一剂，水煎服', is_favorite: true, sort_order: 0,
    default_herbs: [
      { herb_name_pinyin: 'Chai Hu', herb_name_chinese: '柴胡', dosage_grams: 10 },
      { herb_name_pinyin: 'Bai Shao', herb_name_chinese: '白芍', dosage_grams: 12 },
      { herb_name_pinyin: 'Dang Gui', herb_name_chinese: '当归', dosage_grams: 10 },
      { herb_name_pinyin: 'Fu Ling', herb_name_chinese: '茯苓', dosage_grams: 15 },
      { herb_name_pinyin: 'Bai Zhu', herb_name_chinese: '白术', dosage_grams: 10 },
      { herb_name_pinyin: 'Gan Cao', herb_name_chinese: '甘草', dosage_grams: 6 },
      { herb_name_pinyin: 'Bo He', herb_name_chinese: '薄荷', dosage_grams: 3, processing_method: '后下' },
      { herb_name_pinyin: 'Sheng Jiang', herb_name_chinese: '生姜', dosage_grams: 3 },
    ],
  },
  {
    id: 'f2', name_pinyin: 'Si Jun Zi Tang', name_chinese: '四君子汤', category: '补气',
    instructions: '每日一剂，水煎服', is_favorite: true, sort_order: 1,
    default_herbs: [
      { herb_name_pinyin: 'Ren Shen', herb_name_chinese: '人参', dosage_grams: 10 },
      { herb_name_pinyin: 'Bai Zhu', herb_name_chinese: '白术', dosage_grams: 10 },
      { herb_name_pinyin: 'Fu Ling', herb_name_chinese: '茯苓', dosage_grams: 10 },
      { herb_name_pinyin: 'Gan Cao', herb_name_chinese: '甘草', dosage_grams: 6, processing_method: '炙' },
    ],
  },
  {
    id: 'f3', name_pinyin: 'Liu Wei Di Huang Wan', name_chinese: '六味地黄丸', category: '补肾阴',
    instructions: '每日一剂，水煎服', is_favorite: true, sort_order: 2,
    default_herbs: [
      { herb_name_pinyin: 'Shu Di Huang', herb_name_chinese: '熟地黄', dosage_grams: 24 },
      { herb_name_pinyin: 'Shan Zhu Yu', herb_name_chinese: '山茱萸', dosage_grams: 12 },
      { herb_name_pinyin: 'Shan Yao', herb_name_chinese: '山药', dosage_grams: 12 },
      { herb_name_pinyin: 'Ze Xie', herb_name_chinese: '泽泻', dosage_grams: 9 },
      { herb_name_pinyin: 'Mu Dan Pi', herb_name_chinese: '牡丹皮', dosage_grams: 9 },
      { herb_name_pinyin: 'Fu Ling', herb_name_chinese: '茯苓', dosage_grams: 9 },
    ],
  },
]

export const isDemoMode = !import.meta.env.VITE_SUPABASE_URL
